### ISSUE TITLE
conversion fails

### ISSUE THREAD

**Issue by nickolasclarke** [shotazc/pinyin2epub#3]
When I attempt to run the script it creates the directory structure, but then failed out with this the following:

```
python pinyin2epub.py
('santi', 'santi.epub')
Traceback (most recent call last):
  File "pinyin2epub.py", line 157, in <module>
    unzippen(filename)
  File "pinyin2epub.py", line 24, in unzippen
    inputFile.extractall()
  File "/usr/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1082, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "/usr/lib/python2.7/zipfile.py", line 951, in open
    zef_file = open(self.filename, 'rb')
IOError: [Errno 2] No such file or directory: 'santi.epub'
```

the original epub is left in place at the root of the directory.

**Comment by shotazc** [comment]
It seems that you use Python 2.7.
You try use Python 3 series, insted of Python 2.

And, you put epub file in same directory of pinyin2epub.py.

>>the original epub is left in place at the root of the directory.
If "the root of the directory" means same directory of pinyin2epub.py it's fine.

**Comment by nickolasclarke** [comment]
That did it. May want to add that to the README as well. I put in a pull request to reflect some typos.
